name: Build and Test on push to master or PR
on:
    push:
        branches:
        - master
        - '**-support'
        paths-ignore:
        - LICENCE
        - README.md
        - .gitignore
        - AuthoringTool/electron.manifest.json
    pull_request:
  
jobs:
    build-and-test:
        strategy:
            matrix:
                os: [ubuntu-latest, windows-lates, macos-latest]
                dotnet-version: ['8.x']
        runs-on: ${{ matrix.os }}
        name: Build and Test on ${{ matrix.os }} with .NET Core ${{ matrix.dotnet-version }}
        env:
            NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: ${{ matrix.dotnet-version }}
                  cache: true
            - run: dotnet restore --locked-mode
            - run: dotnet build --configuration Release --no-restore
            - run: dotnet test --configuration Release --no-restore --no-build
  
  